package it.polimi.ingsw.model.power;

import it.polimi.ingsw.model.*;

import java.util.ArrayList;
import java.util.List;

public class HypnusPower extends PowerStrategy {
    /**
     * This method prune the action tree generated by the other player.
     * In this case it checks if one worker of the other player is higher than other worker. If this is true is called a
     * method to avoid action of the first worker.
     * @param board the current game board
     * @param myself that player that use the power
     * @param other the opponent player that play the actual turn
     * @param myLastTurn the last turn played by myself player
     * @param otherActionTree the action tree generate by opponent player
     */
    public void pruneOtherActionTree(Board board, Player myself, Player other, Turn myLastTurn, ActionTree otherActionTree){
        Worker m = other.getWorker(Sex.MALE);
        Worker f = other.getWorker(Sex.FEMALE);
        if(m.getSpace().getLevel() > f.getSpace().getLevel()){
            //male worker can't move
            prune(otherActionTree, m);
        }else if(f.getSpace().getLevel() > m.getSpace().getLevel()){
            //female worker can't move
            prune(otherActionTree, f);

        }
    }

    /**
     * This method erases every possibility of the blocked worker to do action pruning the action tree.
     * @param root the action tree of other player
     * @param blockedWorker the worker that can't move of the other player
     */

    public void prune(ActionTree root, Worker blockedWorker){

        List<ActionTree> childrenToRemove = new ArrayList<>();
        for(ActionTree child: root.getChildren()){
            if(child.getAction().getWorkerID().equals(blockedWorker.toString())){
                //prune branch
                childrenToRemove.add(child);
            }
        }
        for(ActionTree child: childrenToRemove){
            root.removeChild(child);
        }
        if(!root.isWin() && root.getChildren().size()==0){
            // lose
            root.setLose(true);
            root.setEndOfTurn(true);
        }
    }
}
